FROM node:14.17.0-alpine

ENV PATH /app/node_modules/.bin:$PATH

ARG REACT_APP_BACKEND_WEBSOCKET_URL
ENV REACT_APP_BACKEND_WEBSOCKET_URL=$REACT_APP_BACKEND_WEBSOCKET_URL

ARG REACT_APP_BACKEND_API_URL
ENV REACT_APP_BACKEND_API_URL=$REACT_APP_BACKEND_API_URL

WORKDIR /app

COPY package.json yarn.lock /app/

RUN yarn install --network-timeout 1000000

COPY ./ /app/

RUN apk add --no-cache git

CMD ["yarn", "start"]